### ISSUE TITLE
gambar

### ISSUE THREAD

**Issue by AbdoelMadjid** [Anamcoollzz/laravel-10-template#1]
untuk gambar logo dan icon profil tidak muncul

**Comment by AbdoelMadjid** [comment]
![2024-07-05_174024](https://github.com/Anamcoollzz/laravel-10-template/assets/2272221/d8d18dc2-97a6-49ce-b25d-6ec005bfbdbe)

**Comment by Anamcoollzz** [comment]
@AbdoelMadjid coba jalanin `php artisan storage:link`
Atau sekalian pakai yg versi 11 https://github.com/Anamcoollzz/laravel-11-template

**Comment by AbdoelMadjid** [comment]
thanks, sudah mantaaap. 

izin modifikasi
